// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_GP0rODn70jwDXrpqiyK-ysShqWZwj5s',
    appId: '1:469215141353:web:5b83db0aeac34a57fbbf78',
    messagingSenderId: '469215141353',
    projectId: 'healthsphere-359a9',
    authDomain: 'healthsphere-359a9.firebaseapp.com',
    storageBucket: 'healthsphere-359a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSJfb41XcrIkCa-_Oq39bL4kYBlc3_2f0',
    appId: '1:469215141353:android:77779ba50d8f51e7fbbf78',
    messagingSenderId: '469215141353',
    projectId: 'healthsphere-359a9',
    storageBucket: 'healthsphere-359a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Myv6YzR1_omBfUjaFfQ81FIFY5ACnqU',
    appId: '1:469215141353:ios:f9fecf747373f6c9fbbf78',
    messagingSenderId: '469215141353',
    projectId: 'healthsphere-359a9',
    storageBucket: 'healthsphere-359a9.appspot.com',
    iosBundleId: 'com.revca.healthsphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Myv6YzR1_omBfUjaFfQ81FIFY5ACnqU',
    appId: '1:469215141353:ios:f9fecf747373f6c9fbbf78',
    messagingSenderId: '469215141353',
    projectId: 'healthsphere-359a9',
    storageBucket: 'healthsphere-359a9.appspot.com',
    iosBundleId: 'com.revca.healthsphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_GP0rODn70jwDXrpqiyK-ysShqWZwj5s',
    appId: '1:469215141353:web:1677c0f6a3534275fbbf78',
    messagingSenderId: '469215141353',
    projectId: 'healthsphere-359a9',
    authDomain: 'healthsphere-359a9.firebaseapp.com',
    storageBucket: 'healthsphere-359a9.appspot.com',
  );

}